name: Ubuntu build using pip packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run : |
        python -V
        python -m pip install --upgrade pip
      
    - name: Install aqtinstall
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install Qt 6.7.3
      run: |
        aqt list-qt linux desktop
        aqt list-qt linux desktop --arch 6.7.3
        aqt install-qt linux desktop 6.7.3 gcc_64
        qmake --version

    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip list

    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
  
    - name: Run tests
      env:
        LD_LIBRARY_PATH: ${{ env.QT_ROOT_DIR }}/lib:${{ env.LD_LIBRARY_PATH }}
        QT_QPA_PLATFORM: minimal
        VEUSZ_INPLACE_TEST: 1
      run: |
        tests/runselftest.py
