name: Ubuntu build using pip packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run : |
        python -V
        python -m pip install --upgrade pip
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'qt-ubuntu-v2'
        version: '6.7.1'
        setup-python: false
    - name: Install Python dependencies
      run: |
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install numpy PyQt6==6.7.1 sip astropy h5py tomli
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
    - name: Run tests
      env:
        LD_LIBRARY_PATH: ${{ env.QT_ROOT_DIR }}/lib:${{ env.LD_LIBRARY_PATH }}
        QT_QPA_PLATFORM: minimal
        VEUSZ_INPLACE_TEST: 1
      run: |
        tests/runselftest.py
